# Generated by Django 4.1.3 on 2025-12-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=7)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vin', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('style', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'vehicle',
                'managed': True,
                'unique_together': {('vin', 'brand', 'model', 'style')},
            },
        ),
        migrations.CreateModel(
            name='Transmissions',
            fields=[
                ('trans_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, max_length=5, null=True)),
                ('supplier_id', models.CharField(max_length=5)),
                ('supplier_name', models.CharField(max_length=20)),
                ('trans_date', models.DateField()),
            ],
            options={
                'db_table': 'transmissions',
                'managed': True,
                'unique_together': {('trans_id', 'supplier_id', 'supplier_name', 'trans_date')},
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('style', models.CharField(max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'price',
                'managed': True,
                'unique_together': {('brand', 'model', 'style')},
            },
        ),
        migrations.CreateModel(
            name='Engines',
            fields=[
                ('engine_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, max_length=5, null=True)),
                ('supplier_id', models.CharField(max_length=5)),
                ('supplier_name', models.CharField(max_length=20)),
                ('engine_date', models.DateField()),
            ],
            options={
                'db_table': 'engines',
                'managed': True,
                'unique_together': {('engine_id', 'supplier_id', 'supplier_name', 'engine_date')},
            },
        ),
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('dealer_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('dealer_name', models.CharField(max_length=20)),
                ('dlpasswd', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'dealers',
                'managed': True,
                'unique_together': {('dealer_id', 'dealer_name', 'dlpasswd')},
            },
        ),
        migrations.CreateModel(
            name='DealerInventory',
            fields=[
                ('dealer_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('dealer_name', models.CharField(max_length=20)),
                ('buy_in_date', models.DateField()),
                ('vin', models.ForeignKey(db_column='vin', on_delete=django.db.models.deletion.DO_NOTHING, to='company.vehicle')),
            ],
            options={
                'db_table': 'dealer_inventory',
                'managed': True,
                'unique_together': {('dealer_id', 'buy_in_date', 'vin')},
            },
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'admins',
                'managed': True,
                'unique_together': {('admin_name', 'passwd')},
            },
        ),
        migrations.CreateModel(
            name='PlantInventory',
            fields=[
                ('plant_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=20)),
                ('assembly_date', models.DateField()),
                ('vin', models.ForeignKey(db_column='vin', on_delete=django.db.models.deletion.DO_NOTHING, to='company.vehicle')),
            ],
            options={
                'db_table': 'plant_inventory',
                'managed': True,
                'unique_together': {('plant_id', 'assembly_date', 'vin')},
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('vin', models.OneToOneField(db_column='vin', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='company.vehicle')),
                ('color', models.CharField(max_length=10)),
                ('engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.engines')),
                ('trans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.transmissions')),
            ],
            options={
                'db_table': 'options',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('deal_date', models.DateField(primary_key=True, serialize=False)),
                ('cust_id', models.CharField(max_length=5)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.dealerinventory')),
                ('vin', models.ForeignKey(db_column='vin', on_delete=django.db.models.deletion.DO_NOTHING, to='company.vehicle')),
            ],
            options={
                'db_table': 'deal',
                'managed': True,
                'unique_together': {('deal_date', 'dealer', 'vin', 'cust_id')},
            },
        ),
    ]
